6-1 решение
js-tasks-ru/jsbasic-20220606_alisa-kostina pull request #9
Opened 2022-07-03 10:32 UTC by aliceecila-oh

2022-07-03 10:33 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2022-07-03 10:35 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-07-03 11:02 UTC, koalex requested changes
Пока не будет решено 6-2 я не смогу принять PR

2022-07-03 14:11 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2022-07-03 14:13 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-07-04 18:38 UTC, koalex requested changes
Нужно решить 6-3

2022-07-05 08:21 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2022-07-05 17:46 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-07-06 06:29 UTC, koalex requested changes
Я не могу принять PR пока не будет решён **7-1**

2022-07-06 10:33 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2022-07-06 11:16 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-07-06 14:58 UTC, koalex requested changes
Теперь нужно решить **7-2**. Не добавляйте пожалуйста след задачи пока я не приму этот  PR

2022-07-06 19:37 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2022-07-07 07:37 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-07-08 11:55 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2022-07-08 14:55 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-07-10 10:42 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2022-07-10 10:46 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-07-10 12:02 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2022-07-11 10:35 UTC, koalex approved these changes

2022-07-11 10:37 UTC, merged